name: maskgit
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit==11.7
  - pytorch==1.13.0
  - torchvision==0.14.0
  - pytorch-cuda=11.7
  - pip:
      - packaging==21.3
      - torch-fidelity
      - torchmetrics
      - matplotlib
      - seaborn
      - opencv-python==4.8.0.74
      - tqdm
      - pillow
      - scikit-learn
      - clip
      - pytorch-lightning==1.0.8
      - omegaconf==2.0.0
      - einops==0.3.0
      - webdataset
      - huggingface_hub